DROP DATABASE IF EXISTS FoundryDB;

CREATE DATABASE IF NOT EXISTS FoundryDB;

USE 'FoundryDB';

CREATE TABLE IF NOT EXISTS users(
id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
email VARCHAR(255) NOT NULL UNIQUE,
pass VARCHAR(255) NOT NULL,
first VARCHAR(45) NOT NULL,
last VARCHAR(45) NOT NULL,
url VARCHAR(100) DEFAULT 'https://acrobatusers.com/assets/images/template/author_generic.jpg',
area VARCHAR(5) NOT NULL,
num VARCHAR(10) NOT NULL,
salt VARCHAR(50) NOT NULL,
tutor INT NOT NULL
);