DROP DATABASE IF EXISTS OADB;

CREATE DATABASE IF NOT EXISTS OADB;

USE 'OADB';

CREATE TABLE IF NOT EXISTS users(
id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(45) NOT NULL,
smuId INT NOT NULL DEFAULT 11111111,
recipientId INT NOT NULL DEFAULT -1,
secretSanta INT NOT NULL DEFAULT -1
);